### ISSUE TITLE
instrument colorization

### ISSUE THREAD

**Issue by jhlusko** [kosua20/MIDIVisualizer#107]
Great project!

Potential extension: colorizing the midi file by channel or instrument (for multi-channel/instrument midi files).

**Comment by kosua20** [comment]
Hello, thank you for using MIDIVIsualizer!

If I understood your suggestion correctly, you can already achieve this in MIDIVisualizer (since v5.2): 

* in the 'Notes' section, enable 'Per-sets colors'
* in the 'Define sets' dropdown, you will then be able to define what is a set : either per-channel, per-track, per-key, or using an arbitrary note to split the keyboard in two sets.  <img width="568" alt="Capture 2021-10-31 à 12 11 58" src="https://user-images.githubusercontent.com/3199516/139580202-846d0fa5-d81f-48b0-bf17-9469fff032ce.png">

* all color settings are now replaced by dropdowns where you can specify 8 colors, one for each set  <img width="168" alt="Capture 2021-10-31 à 12 12 11" src="https://user-images.githubusercontent.com/3199516/139580212-560b3f8c-44d6-49cf-87b5-a2834723f65f.png">

I know that this setting is a bit hidden and that the labels are probably unclear, so I would welcome any suggestion to improve this 🙂 

Please let me know if this helped (or if I misunderstood your suggestion)!

**Comment by jhlusko** [comment]
Perfect, thanks!
