### ISSUE TITLE
unable to edit /ressources folder 

### ISSUE THREAD

**Issue by turboman1** [kosua20/MIDIVisualizer#2]
Hi there,

I'm trying to make changes to the contents in this folder:  https://github.com/kosua20/MIDIVisualizer/tree/master/ressources

However nothing happens when I run `make`.
Is there another command to compile this folder?

Thanks!

**Comment by kosua20** [comment]
Hi,
to directly include the resources in the executable I've stored the raw images and the shaders strings in source files in `src/ressources`. The Resources manager builds a list of the available resources at initialization (see [ResourcesManager.cpp:43](https://github.com/kosua20/MIDIVisualizer/blob/a7c066d80a987adad350298b2a43bcee6a5a9906/src/helpers/ResourcesManager.cpp#L43) ).
I have not included the scripts to generate the cpp files, but I'll see if I can dig them up and add them to the repository.

**Comment by turboman1** [comment]
That would be great, thanks.

**Comment by turboman1** [comment]
Is shaders.cpp generated from the code in /resources/shaders.txt?

**Comment by kosua20** [comment]
The package utility doesn't do it yet, but that's the idea in the near future, yes.

**Comment by kosua20** [comment]
I've added the *shaders.cpp generation from shaders.txt* part to the packaging utility. It's quite sensitive to the input format, I will clean this further down the road. I think the best way would be to split shaders.txt in multiple .vert/.frag files, and just aggregate them in the packaging utility.

**Comment by turboman1** [comment]
Ah great, thank you.   In what way is it sensitive?

**Comment by kosua20** [comment]
Thinking about it again, it wasn't very satisfying to have all shaders in one huge `.txt` file with some additional quotes and brackets. So I've split the shaders into multiple files, in `ressources/shaders`, one for each vertex and each fragment shader. That way they are easier to edit (that was the original setup before I started cleaning the resources directory). 
Now, the packager will load them (look at the beginning of `src/packager.cpp` for the list of shader names) and output them to `src/ressources/shaders.cpp`, overwriting it. I think this will be cleaner this way.

To summarize:
- the 3 images should be put in `ressources/`
- the 6*2 shaders should be put in `ressources/shaders/`
- the packaging utility has a list of names to look for.
- running it with `make package` will overwrite all source/header files in `src/ressources/`.
- you can then rebuild the executable with the updated data by running `make midiviz`

If you want to add *additional images or shaders*:
- put them in `ressources/` and `ressources/shaders` respectively.
- update the listings at the beginning of `main()` in `packager.cpp`.
- update the ResourcesManager ([ResourcesManager.cpp:43](https://github.com/kosua20/MIDIVisualizer/blob/a7c066d80a987adad350298b2a43bcee6a5a9906/src/helpers/ResourcesManager.cpp#L43)) so that it knows about the new image names and sizes (for shaders it's automatic). This step could be avoided by outputting more infos to the data.h file, but this is left as a future improvement.
