### ISSUE TITLE
Support live/realtime midi

### ISSUE THREAD

**Issue by pnomolos** [kosua20/MIDIVisualizer#39]
Is support planned to listen on a midi port/ports and process the visuals there as opposed to loading a midi file?

**Comment by og2t** [comment]
On a similar note, is it possible to hear/stream MIDI notes, so they can be heard?

**Comment by kosua20** [comment]
Those suggestions are very interesting but will require more work than I could currently dedicate to this project, so I don't want to promise anything :)

Playing the MIDI notes using the system MIDI bank should be possible with something like rtmidi, but if anybody knows of similar multi-platforms libraries for playback I'm interested.

Supporting streaming is an interesting challenge because I would have to change the visualisation (right now we see the notes scrolling down before they are played, while with streamed notes it would probably be the reverse). I'll think about it and see if/how this can fit with the current visualisation.

**Comment by asl97** [comment]
@kosua20 depending on the use case, you might not even need to change the visualization,
for example, just "buffer" (delay) the input.

Use case could be live streaming (by delay the live feed to sync with the viewer),
Or simply playback, like aplaymidi > MIDIVisualizer > synth.

**Comment by cptwilson** [comment]
Fluidsynth (or Timidity++ even, although its a bit dated) can do software wavetable MIDI playback in realtime (or low-latency, good enough for visualising) using Soundfonts. Its cross-platform as well.

**Comment by vaclavmuller** [comment]
This is how I use Synthesia:
MIDI IN: keyboard
MIDI OUT: keyboard

Practice Melody mode means that the program waits for pressing of the correct key.
The program can exclude played notes from sending to MIDI OUT.

**Comment by pi-kei** [comment]
I did a fork with live mode. It works, but need some minor improvements. It uses RtMidi17 to get live midi messages from midi keyboard in my case.

**Comment by kosua20** [comment]
Hello everyone, I'm happy to say that [version 6.0](https://github.com/kosua20/MIDIVisualizer/releases/latest) is adding support for live mode. You should now be able to select a MIDI device to "listen to" in the interface of MIDIVisualizer.

**Comment by LimonAstuto** [comment]
Ops I see now, that my suggestion is already here! Do I delete mine? Thank you

> 
> 
>I would have to change the visualisation (right now we see the notes scrolling down before they are played, while with streamed notes it would probably be the reverse). I'll think about it and see if/how this can fit with the current visualisation.
