### ISSUE TITLE
Particles disappearing

### ISSUE THREAD

**Issue by turboman1** [kosua20/MIDIVisualizer#5]
The particles seem to be abruptly disappearing when the same note is struck in succession.  Any guidance on how to correct this? 

thanks!

**Comment by kosua20** [comment]
Hello,
You noticed right! This is because for now there is only one "particles set" per key on the piano. So if there are two notes following quickly on the same track, the particles of the first one are going to be reset when displaying the second one.
This was done for performance reasons and avoid spawning too much geometry while rendering, but could be solved with a global pool of particles.
I'll think about it but can't promise anything in the near future.

I'll keep this issue updated.

**Comment by turboman1** [comment]
thanks!

**Comment by kosua20** [comment]
Hello, the problem has been solved in release 2.1. Technically there is still a limit on the number of notes simultaneously emitting particles, but it's much higher.

I've updated the [Releases page](https://github.com/kosua20/MIDIVisualizer/releases). Please let met know if you encounter any issue!

**Comment by PeterPiano** [comment]
Thanks very much.
*Trung Tâm Âm Nhạc Hùng Music  - hungmusic.com <http://hungmusic.com>*
*198/59 Đường Số 3 - Phường 9 - Gò Vấp - Tp.HCM - **ĐT: 0964.927.464*
*Vietcombank CN Hồ Chí Minh*
*STK: 0501000016482 (Nguyen Viet Hung)*
*Facebook*: https://www.facebook.com/musicbox205
*Đăng Ký Kênh Học Online Miễn Phí*: https://www.youtube.com/hungmusic



Vào Th 4, 10 thg 10, 2018 vào lúc 00:58 Simon Rodriguez <
notifications@github.com> đã viết:
