### ISSUE TITLE
Forking this repo for a different KB layout

### ISSUE THREAD

**Issue by philiprhoades** [kosua20/MIDIVisualizer#53]
People,

I know a bit about C but less about C++ but can someone comment on the possibility of forking this code and changing it so it would work with the attached KB layout?

![Screenshot_2020-06-25_03-06-01_AXiS-49_KB_Layout](https://user-images.githubusercontent.com/1153703/85605785-d9485500-b695-11ea-9564-ac5c2a9ae193.png)

Thanks,

Phil.

**Comment by kosua20** [comment]
Hello, 
right now the keyboard is rendered in a shader, where each pixel determines which key it is covered by, and check if the key is enabled in a global array. This is doable because it's mainly a matter at looking at the X coordinate of the pixel (and the Y for minor notes) to obtain the "regular" linear keyboard key ID.
To support this hexagonal pattern, you need a way to obtain the key ID from the pixel (x,y) location. This could be built from a cartesian to hexagonal mapping (see for instance https://www.shadertoy.com/view/XdSyzK).
For the text it's a bit more complex right now, as this is not supported on the linear keyboard either.

I hope this helps!

**Comment by philiprhoades** [comment]
@kosua20 ,

Yes - thanks for the info!
