### ISSUE TITLE
After VC.REDIST.X86 & 64 No Application

### ISSUE THREAD

**Issue by Sonobree** [kosua20/MIDIVisualizer#70]
Hello, i hope you can help me.
1. I downloaded master zip.
2. I downloaded midi visualizer.
... wanted to start... VR Runtime.dll was missing.

3. I´ve read the issues and downloaden VC.REDIST86 & 64 and installed both.
4. resarted laptop mit windows 10 home
5. Midi Visualizer didn´t start again. Shows same problem... no vr.runtime.dll.
6. I was looking for them "Windows/System32/" and found the dll.

Don´t get the problem? Can you help me please?
Thanks.

kind regards....

**Comment by MysticPiano** [comment]
@Sonobree 



Hello Sonobree. Welcome to Github, I see that this is your first issue, so congratulations on opening your first one.

My name Is Mystic And I could help you with this issue


Well, Can you please send me a screenshot of your system specs in control panel? You can find this in control panel by going to the following directory in control panel - Control Panel\System and Security\System


![image](https://user-images.githubusercontent.com/68113615/96585194-dc2e1c00-12fc-11eb-9bac-e51b6c2c000f.png)
Can you also Send me a screenshot of the error?


![image](https://user-images.githubusercontent.com/68113615/96585365-21524e00-12fd-11eb-8896-844de3ddeb0a.png)
Note that I am A COMMUNITY MEMBER and am helping you since I like this program and I have a lot of free time. I am Not the developer of this program nor do I take any credit for fixing these issues. I try to help everyone, but if there is something wrong with the program itself and I don't know how to fix it, I may not be able to help you.

Anyways, please send me the following screenshots for me to help me assist you more expediently

Regards

Mystic

**Comment by Sonobree** [comment]
Hello Mystic,

Thanks so much for your help.
I solved the problem:-)
It was a wrong order of installation.
Greetings,
Georg

MysticPiano <notifications@github.com> schrieb am Di., 20. Okt. 2020, 14:30:

**Comment by MysticPiano** [comment]
@Sonobree I'm glad I could be of help in any way. Please close this issue if you want to and have no other pending problems with this program or thread. Feel free to open another issue and I will help you to the greatest extent.

**Comment by kosua20** [comment]
Thank you MysticPiano for your help with this ! I'm closing it now, once again thank you :)
