### ISSUE TITLE
Rollback speed

### ISSUE THREAD

**Issue by intmainreturn00** [kosua20/MIDIVisualizer#72]
It would be awesome if we could set the speed of playing, like x2, x3, x0.5, etc. Would be useful for learning new scores in slow mode playing.

**Comment by MysticPiano** [comment]
@intmainreturn00 I don't think that is possible. MIDI Visualizer reads midi and Makes it into GFX. It is not a learning tool

The slower mode would mean incorporating Synthesia - type features. This may also need live midi for learning and an extra asset like some learning pack and GFX pack. The learning pack would contain features like LIVE Midi,  Playback Speed and wrong note Detection. The GFX pack is the tool that is there in the releases today. LIVE MIDI is a feature that @kosua20 (Developer of this tool) has added to his future features list for this tool.

I really like your suggestion though as there is no software as easy to use and download as MIDI Visualizer.

If this is being added to MIDI visualizer, the developer will have to do a lot of work and time into this project.

If you really need this urgently, download a video editor (shotcut or adobe premier pro) and speed up or slow down a rendered video in the editor and try to practice. You don't necessarily have to render/export the video. 

Note that I am A COMMUNITY MEMBER and am helping you since I like this program and I have a lot of free time. I am Not the developer of this program nor do I take any credit for fixing these issues. I try to help everyone, but if there is something wrong with the program itself and I don't know how to fix it, I may not be able to help you. If you need any more help, with anything reply and I will respond within 48 hours

**Comment by vaclavmuller** [comment]
Alternatively - you can slow-down the midi file before rendering of the video.

**Comment by kosua20** [comment]
Hello @intmainreturn00, and thank you for your suggestion! My apologies for the late answer, I currently have many things on my plate outside of MIDIVisualizer 😄 
Custom playback speed could be added quite easily, along with support for it when exporting videos. I'm adding it to the next release list, I'll update you if/when it's done!

**Comment by kosua20** [comment]
Hello again, [release 5.3](https://github.com/kosua20/MIDIVisualizer/releases/latest) now support custom playback speed! You can slow down or speed up the playback using a slider in the interface. You can also Ctrl+Click on the slider to input a specific value.
