### ISSUE TITLE
Save background image to config file

### ISSUE THREAD

**Issue by 4321ba** [kosua20/MIDIVisualizer#73]
This project is so cool!

**Describe the issue**
Edit: My original problem is that when I load a bg image and save a config file, restart and load the config file, the image isn't there, while all the other visual changes are (likely including the other options for background image like bg opacity), and this seems like a bug (it might be intentional though).

My goal is to load a background image from command line, it would be the easiest if it could be defined in the config file.
I was searching through the options and I couldn't find a way to do either of them.
I will be trying to automate the export from the command line and my guess is that I can't have a background image at the moment if I try to do that. Did I miss something?

**Hardware info:**
- OS: Ubuntu 20.04
- MIDIVisualizer version v5.2
- GPU model: Nvidia GeForce 750

**Comment by MysticPiano** [comment]
@4321ba It may be possible by ./MIDIVisualizer --help and checking all the commands. 

I feel it is something like --bg. I am not really sure as I use the executable package

If you can't get it to happen with any command line, A config file might help, but it wont store the background's location/path.

I recommend you to download the latest executable (.exe) version of MIDI Visualizer for usage, If you haven't made any alterations to MIDI Visualizer for your needs. If you have messed with the code for your own needs, well I cannot help.

Note that I am A COMMUNITY MEMBER and am helping you since I like this program and I have a lot of free time. I am Not the developer of this program nor do I take any credit for fixing these issues. I try to help everyone, but if there is something wrong with the program itself and I don't know how to fix it, I may not be able to help you. If you need any more help, with anything reply and I will respond within 48 hours

**Comment by 4321ba** [comment]
@MysticPiano Thanks for your comment!
I tried looking at the --help flags but I couldn't find a way to load the image.
„A config file might help, but it wont store the background's location/path” yes, I edited the comment to clarify that that's actually the bug I tried to explain.

**Comment by MysticPiano** [comment]
@4321ba Why dont you try the executable? It is faster and requires less effort to operate?

**Comment by 4321ba** [comment]
@MysticPiano I am using the (linux) executable (without modifications), I'm just planning to make a bunch of Youtube videos and I'd also like to improve in shell scripting and that's why I'd like to automate it, and it's not actually a problem if I don't have a background image, I don't care about it that much.

**Comment by MysticPiano** [comment]
@4321ba As an Alternative, you could use a video editor to mask out the background

**Comment by 4321ba** [comment]
@MysticPiano Yes, I could use that too, or export manually, but I'm fine with the black bg for now. Thanks for the suggestion though!

**Comment by MysticPiano** [comment]
Okay. Glad I could help.

**Comment by kosua20** [comment]
Hello, thank you for your feedback! Indeed for now every setting that relates to image files on disk is not loaded from/saved to the configuration file and cannot be specified from the command line. I can add support for these with a bit of extra handling, I'll let you know if/when this is added to MIDIVisualizer.

**Comment by kosua20** [comment]
Hello again, I've added support for this in [release 5.3](https://github.com/kosua20/MIDIVisualizer/releases/latest). If you export a configuration file it will now export the image path, and it will be loaded back when loading a config file. You can also use the `--bg-img-path` flag from the command-line, specifying the absolute path to the image.

**Comment by 4321ba** [comment]
Thank you very much! I'll be using this from now on. I tried it and works as expected so I'll close this.
Also, if you're interested, I made quite a few videos with this tool: https://www.youtube.com/playlist?list=PLDa4Vj43E2e-mCukFLGM5xTLILNZ_daaI , it works great!
