### ISSUE TITLE
MIDI Visualizer Update 

### ISSUE THREAD

**Issue by MysticPiano** [kosua20/MIDIVisualizer#80]
(TO BE PINNED @kosua20 )

Welcome to MIDI Visualizer Issues/Enhancements.

****************************************************************************************************************************************
If you have an issue, please search through all the issues and you may hopefully find one that solves your issue, if not, just create a new issue/enhancement and someone in the community like me  or the developer (@kosua20 ) will get back to you.  
****************************************************************************************************************************************
Updates are frequent and bring many features, so make sure to update to the newest version of MIDI Visualizer.
****************************************************************************************************************************************
This issue will be updated after every update to MIDI Visualizer, and all issues that have been fixed will be tagged on the update page.
****************************************************************************************************************************************

**Comment by MysticPiano** [comment]
Download Version 5.3 Here  - https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.3

Release Date - 26/11/2020

**Comment by MysticPiano** [comment]
Download Version 5.3(1) here - https://github.com/kosua20/MIDIVisualizer/releases/tag/v5.3(1)

Fixes a few render issues

Release Date - 28/11/2020

**Comment by MysticPiano** [comment]
Download Version 6.0 Here - https://github.com/kosua20/MIDIVisualizer/releases/tag/v6.0

Live MIDI integrated. 

Release date - 4/11/2020

**Comment by kosua20** [comment]
I'm going to close this topic because I want to keep only addressable issues in the list, and having to update this manually for each release would be bothersome. Furthermore, the [Releases page](https://github.com/kosua20/MIDIVisualizer/releases) already lists releases along with their detailed changelog.
To make sure people are aware of the latest release, I've added a link to the releases page at the top of the readme.
The message shown to people when creating an issue also points them to the releases page, the troubleshooting section of the readme and the existing issues list. That should cover most cases where the release list is needed.

Now that I think of it, maybe adding the readme and or changelog to the downloadable releases could also be a good thing, I'll see what I can do. Thank you for your suggestions and your help with this! 😃
