### ISSUE TITLE
Notes setting adjusts the same notes and minor color

### ISSUE THREAD

**Issue by ndma-ucsc** [kosua20/MIDIVisualizer#84]
Notes and Minor colors adjust at the same time, resulting in the same color for both. However, keyboard setting can have custom colors for both.

**Hardware info:**
- OS: Windows 10 Home
- MIDIVisualizer 6.0
- NVIDIA GeForce 1650 Max-Q Design
- 32GB

**Comment by MysticPiano** [comment]
@ndma-ucsc Hello and Welcome to MIDI Visualizer Issues.

If you want to set different note colors, you can deselect the option - Sync Effect Colors
![image](https://user-images.githubusercontent.com/68113615/101732438-3a000880-3ae3-11eb-96ae-8247651d1bc2.png)
Alternatively, If you would like to split the Piano, you can do so, by defining a set here.
![image](https://user-images.githubusercontent.com/68113615/101732559-6ae03d80-3ae3-11eb-8ffd-8acb2856c59d.png)
Just make sure to have the Per - Set Colors Checked.

Did That help?

Note that I am A COMMUNITY MEMBER and am helping you since I like this program and I have a lot of free time. I am Not the developer of this program nor do I take any credit for fixing these issues. I try to help everyone, but if there is something wrong with the program itself and I don't know how to fix it, I may not be able to help you. If you need any more help, with anything reply and I will respond within 48 hours.

 Regards

Mystic Piano

**Comment by ndma-ucsc** [comment]
Ahh now I feel kinda dumb. Thanks that helped.

**Comment by MysticPiano** [comment]
@ndma-ucsc No worries, I am more than happy to help

**Comment by kosua20** [comment]
Hello, no problem and I'm happy that MysticPiano was able to help !
You're not the first person to encounter this specific issue and MIDIVisualizer could be more clear about the fact that colors are kept in sync and how to disable it, I'll see what I can do in a future release.
