### ISSUE TITLE
Note graphics?

### ISSUE THREAD

**Issue by MarkBowenPiano** [kosua20/MIDIVisualizer#88]
First of all, thank you so so much for such an absolutely amazing application. Using it on my YouTube channel (http://www.youtube.com/markbowenpiano) and along with some visual editing in Final Cut Pro it really does help me out massively. 

I was wondering if it would ever at all be possible to have say an input to place a graphic (image / animated gif / looping movie file) so that they would fall down in place of the current note shapes?

Would add so much visually so that let's say you were recording a piece for Christmas you could instead of the notes falling have say a candy cane stick or something like that. Obviously people would need to create the graphics to a certain aspect ratio but would be amazing if that could be added in. 

Just a thought of something to really push the app to the next boundary though. Hoping someone reads this and thinks it's a good idea anyway. 

Once again, thank you so much for such a fantastic application. Very much appreciated. Hope everyone is staying safe in these odd times. 

Best wishes,

Mark

**Comment by MysticPiano** [comment]
@MarkBowenPiano Welcome To MIDI Visualizer Issues.

The Feature that you are talking about is currently not possible. However, to add a candy cane feeling to your videos, You can
a) Mask out the color of the falling notes and add a Candy cane texture Underneath.
b) You can Specify a custom picture as particles. (More in #68)

Hope This Helped. But Yes, This Feature would be really good for youtubers like you and me.

**Comment by 4321ba** [comment]
I also think this would mean a lot visually, even like a gradient color for notes like in synthesia. Plus another similar feature would be a texture for the piano keys. However this doesn't seem very straight-forward to implement, especially if we want nice endings on the top / bottom with like consistency between long and short notes.

**Comment by sreich** [comment]
I completely agree. The biggest complaint I have is, yes..the style of the notes. I want to make it more visually appealing. I was trying to think of how this is done on a technical level. My rendering knowledge isn't vast

I use it for my videos, ( https://www.youtube.com/watch?v=KQQbYu1OBDw )

I'm comparing this tool to https://www.piano-vfx.com/manual/#Effects , piano vfx, and Ember. I think there's another one too that I forget

Biggest priority is I want to get the notes to look like they do there. That neon effect. I don't know exactly how to describe it visually, if it's a mixture of having a border and and inner, that differ in colors?

Looking at it. I think there's a blur/bloom that is added on the outer edges which makes it feel more of a "light", instead of the pastel flat look we have right now. That would be an additional effect, apart from the "note graphic" itself, or any shaders put therein. It looks like we already have that part, but..it behaves strangely. I think we need a separate 'enhancement' created for that part of it. The fading in particular...the bloom should happen all around and be not dependent upon the "fading" value of that "blur notes" checkbox.

As for the graphics themselves...

Ember here https://www.youtube.com/watch?v=2n0IkRRX52w shows an example of that outer/inner border difference

Trying to think, but not sure how to handle these cases, in a way that 'scales' nicely. As opposed to say, hard coding the shaders for every little scenario

@MarkBowenPiano  you don't happen to have sample graphics I can play with, do you? I can make necessary code changes if I have something good to go off of...the ideal would be something transparent that can then be mixed with whatever color we provide it.

**Comment by sreich** [comment]
Okay, I tweaked the code a bit and got this:

![image](https://user-images.githubusercontent.com/1508497/188541988-0e4a0e77-8629-40b7-90c1-01323f0850ca.png)

At least it's a little bit closer than the blocky flat look, towards the end result that I want. Feedback welcome

**Comment by kosua20** [comment]
Hello, notes appearance can now be customized with an outline and background textures in the latest [7.1 release](https://github.com/kosua20/MIDIVisualizer/releases/latest).
