### ISSUE TITLE
Program Shut Down Automatically On Exporting

### ISSUE THREAD

**Issue by bazinganic** [kosua20/MIDIVisualizer#95]
Hello @kosua20, thank you for creating such an easy and great midi visualizer tool. The image export function works perfectly for me. The problem I encountered is that the program died immediately every time I tried to export a video version. The device I used was macOS version 10.12.6. 

Here is the error I received: https://docs.google.com/document/d/1tVFp314IcghNLiiYb2z1nEwR4yzZUxl6xtDafsmDLkQ/edit?usp=sharing

I look forward to your reply. Thank you so much!

**Comment by kosua20** [comment]
Hello, thank you for reporting this issue and sending the detailed error. I believe I've found the source of the problem and this should be fixed with the latest [6.3 release](https://github.com/kosua20/MIDIVisualizer/releases/latest). Please let me know if you still encounter issues with this new version.
